import CACHE_PER_BUILD_HEADERS from "./CACHE_PER_BUILD_HEADERS"
import CORS_HEADERS from "./CORS_HEADERS"
import DATA_HEADERS from "./DATA_HEADERS"
const STANDARD_HEADERS = {
    ...CACHE_PER_BUILD_HEADERS,
    ...CORS_HEADERS,
    ...DATA_HEADERS,
}
export default STANDARD_HEADERS
