/* eslint-disable react/jsx-key */
import { ReactNode } from "react"
const SUPPORTERS: ReadonlyArray<{ names: readonly ReactNode[] }> = [
    {
        names: ["Jesse Emrys"],
    },
    {
        names: ["Dawn Bazely", "Marc Cadotte"],
    },
    {
        names: ["Bjarni Sigurðsson", "David Smith", "Pierangelo Pirak", "Roderic Page", "Ronald Dijkman", "Taro Maeda"],
    },
    {
        names: ["Juan C. Opazo"],
    },
    {
        names: [
            "Andrew Farke",
            "Casey Holliday",
            "dpmelters",
            "iamatrombone",
            "Ingo Braasch",
            "Jim Bumgardner",
            "Manabu Bessho-Uehara",
            "Marissa K. Westerfield",
            "Paul Bump",
            "Penny Higgins",
            "Peter Wagnerr",
            "Ryan Timpe",
            "Scott Hartman",
        ],
    },
    {
        names: [
            "Heather Havens-Beardsley",
            "Manabu Sakamoto",
            "Nilese Orre",
            "Stuart Humphries",
            "Susan Havens",
            "Tanja Schwander",
        ],
    },
    {
        names: [
            "Akifumi Tanabe",
            "Bastian Greshake Tzovaras",
            "Tauana Cunha & Bruno de Medeiros",
            "Daniel C. Ilut",
            "Foo Njaball",
            "J. Schnitzler",
            "James Schnable",
            "Kanako Bessho",
            "Kenji Fukushima",
            "Lars Schmitz",
            "lhopitalified",
            "Luis Zaman",
            "Matt Johnson",
            "Matthew Nicotra",
            "mlandis",
            "mya",
            "Norio Miyamoto",
            "Phil Barden",
            "R. J. Smith",
            "Robin Hayward",
            "Samuel Scarpino",
            "skberke",
            "Tracy Heath",
            "Will Cornwell",
        ],
    },
    {
        names: [
            "Akira Kawabe",
            "Benjamin Moon",
            "Darren Parker",
            "Fabien Condamine",
            "Jeff Rubinoff",
            "Jérôme Delroisse",
            "Roest Crollius, Hugues",
            "Yoonsoo Hahn",
        ],
    },
    {
        names: ["Taormina Lepore"],
    },
    {
        names: [
            "Adrian Kingston",
            "Catriona Munro",
            "Graciela Gil-Romera",
            "Johanna Cannon",
            "organelas",
            "Orlando Schwery",
            <cite>Phylogeny Explorer Project</cite>,
            "ReBecca Hunt-Foster",
            "smznbv",
        ],
    },
    {
        names: ["Albert Chen", "Chiaki Jimi", "Jack Wood", "Jake Leyhr", "Karen van Niekerk", "myroomismylibrary"],
    },
    {
        names: [
            "Alex Skeels",
            "Allen Collins",
            "Andrew Rai",
            "António Matos",
            "Brendan Reid",
            "Brooke Weinstein",
            "Bryan Carstens",
            "C. C. Oostdijk",
            "David Clark",
            "David Grossnickle",
            "Francisco Rodriguez-Sanchez",
            "Franz Krah",
            "Guy Leonard",
            "Hiroyo Nishide",
            "Ingrid Oxaal",
            "Jacob Michael Nicosia",
            "James Townsend",
            "Janus Hansen",
            "Jarrod Cusens",
            "Jessica Gray",
            "Jordi Paps",
            "Josef C Uyeda",
            "Joshua Mathews",
            "Juan Gallego-Zamorano",
            "Julien Louys",
            "Kamil Jaron",
            "Laura Soul",
            "Leann M. Biancani",
            "Livio Ruzzante",
            "Lyndon Coghill",
            "Maggie Schedl",
            "Marc Robinson-Rechavi",
            "Mark Blaxter",
            "Meig Dickson",
            "Milton Tan",
            "Nadezhda Rimskaya-Korsakova",
            "Nicholas Matzke",
            "Peter Berx",
            "Pierre Gueriau",
            "Prosanta Chakrabarty",
            "Samy Kamkar",
            "Scott Reid",
            "Sofer Athlan-Guyot",
            "Stephen Smith",
            "T. Clark",
            "t55.eriksson",
            "Universitat de Barcelona Q0818001J",
            "Winston Maxwell Wilson",
        ],
    },
    {
        names: ["Nicolas Snyder"],
    },
    {
        names: ["Dorota Paczesniak", "Kirstin Brink", "Timothy Bartley"],
    },
    {
        names: ["Bethany Allen", "Graeme T. Lloyd ", "Linda Campbell", "Rory Dimond", "Scott Chamberlain"],
    },
    {
        names: [
            "Adam Bewick",
            "Adriane Lam",
            "Ann Priess Maclean",
            "Ben Morris",
            "Benjamin de Bivort",
            "Chris Hamilton",
            "Christina Picchi",
            "Colleen Nell",
            "Connie Taylor",
            "Dakota McCoy",
            "Daniel Godwin",
            "Daniel Newman",
            "David Bapst",
            "David Orr",
            "Gregory James Smith",
            "Hanna Mesraty",
            "Jacquelyn Clagnaz",
            "jamesboy",
            "Jennifer Bauer",
            "Jose Burgos",
            "Kathleen Morrill",
            "Kathryn G Turner",
            "Keith Bayha",
            "Kyle T David",
            "Laura Lagomarsino",
            "Laurence Dumouchel",
            "M. Caitlin Fisher-Reid",
            "maxbw12",
            "Michael McKain",
            "Murielle Ålund",
            "Nathan Upham",
            "Nick Sard",
            "Orlando Schwery",
            "Peter E. Midford",
            "Philipp Ross",
            "reptilerhett",
            "Shahan Derkarabetian",
            "Thomas Hegna",
            "Thomas Rocco Pascucci",
            "Traci Cramer",
            "Wai-Yin Kwan",
            "Yang Zhang",
        ],
    },
    {
        names: ["Chema Martin", "Gwen Antell", "Joseph Brown", "Mark Holder", "Romain Feron", "Seth Finnegan"],
    },
    {
        names: [
            "Aaron Kufner",
            "Alycia Stigall",
            "Andrea Jones",
            "Anjali Kumar",
            "Beckett Sterner",
            "Brian O'Meara",
            "Christine Axon",
            "Claire McWhite",
            "Dave Zucker",
            "David Lovelace",
            "David Weisrock",
            "Emily Jane",
            "Emma Baiada",
            "Gareth Monger",
            "Gaurav Kandlikar",
            "Gavin Leighton",
            "Heather L Johnson",
            "Henry Thomas",
            "iskanderdun",
            "jashapiro",
            "jenemcc",
            "Jon Puritz",
            "Joshua Martin",
            "Katie Collins",
            "Linda Campbell",
            "Luke Thompson",
            "Matt Celeskey",
            "Matt Gitzendanner",
            "Neil P Kelley",
            "Nicolas Medina",
            "Paul Frandsen",
            "Phoebe Cohen",
            "Robert Feranec",
            "Sally Warring",
            "Sandy Kawano",
            "Steven Roberts",
            "Susan Perkins",
            "Tracy Heath",
            "Travis Watson",
            "Troy Chien",
            "Will Gearty",
        ],
    },
    {
        names: [
            "beroe",
            "Christophe Dessimoz",
            "Edward Gaillard",
            "John McCormack",
            "Leonie Färber",
            "Meghan Balk",
            "Morgan Gray",
            "Natalie Cooper",
            "Thea Boodhoo",
            "Tim Triche",
            "Todd Vision",
        ],
    },
    {
        names: [
            "alexmendozasoler",
            "B. Duygu Özpolat",
            "goring",
            "John D'Angelo",
            "jonsan",
            "Lee Stevens",
            "lilychughes",
        ],
    },
    {
        names: ["Juwon S."],
    },
    {
        names: ["Markus G"],
    },
    {
        names: [
            "Benjamin Liebeskind",
            "Benny Borremans",
            "Conor Meehan",
            "Franz Anthony",
            "James Erdman",
            "Jennifer Crees",
            "Kathleen Grogan",
            "Kevin Healy",
            "Kristina Osen",
            "Marymegandaly Daly",
            "Max Maronna",
            "Melissa Esmé Landry Green",
            "Nathan Clark",
            "Paulyn Cartwright",
            "Ricardo Ely",
            "Richard Dalton",
            "wmaddisn",
            "Yuko Ulrich",
        ],
    },
    {
        names: [
            "Alexander Hauser",
            "Benjamin Weigel",
            "Catriona Munro",
            "Eleanor Warren-Thomas",
            "Jakob Vinther",
            "Jane Reeves",
            "Javier Igea de Castro",
            "Joelle Lefort",
            "Jonathan Cramb",
            "Kez Armstrong",
            "Klinsman Hinjaya",
            "Marianne Annonier",
            "Markus Ankenbrand",
            "Martin Dumbrell",
            "Miguel Moreno Azanza",
            "Peter Mulhair",
            "Richard Dearden",
            "Ryan Stamp",
            "Samuel Abalde",
            "Simon Maxwell",
            "Stefania Montalti",
            "Steven Allain",
            "Suraj Menon",
            "Thomas Guillerme",
        ],
    },
    {
        names: ["David Yurkowski", "Keith Johnstone", "Monica Granados", "Stefanie Butland"],
    },
    {
        names: [
            "Aaron Hardin",
            "Alyssa Arre",
            "Andrea Hodgins-Davis",
            "April Wright",
            "Armita Manafzadeh",
            "Bettye Keefer",
            "Bottlegreen Elderflower",
            "Brent Schneeman",
            "Caitlin Redak",
            "calyoung ",
            "Calypte Ascharna",
            "chaprocks",
            "Dan Becker",
            "David Bapst",
            "Delaney Holden",
            "Denver Fowler",
            "Diana Pomeroy",
            "Diego F. Morales-Briones",
            "Eliot Eliot",
            "Evan Boucher",
            "Grace Wilkinson",
            "Hayley Orlowski",
            "Jack Shaw",
            "Janelle Cooper",
            "Jasmine Mah",
            "Jess Stitt",
            "Jessica Ware",
            "Jonathan P. Drury",
            "Kathy Adams",
            "KiRAWRa N",
            "Lexi Crisp",
            "lfrankel17",
            "ljvillanueva",
            "maobley",
            "Matthew Reeves",
            "Maximilian Press",
            "Maximilian Press",
            "MC Hannon",
            "Michael Andersen",
            "Michael Prigge",
            "Oliver Azevedo",
            "Paul Plourde",
            "Paul Steil",
            "rachel.swenie",
            "Rayna Harris",
            "Rebecca Tarvin",
            "rsschwartz",
            "Rutger Jan Wessel Jansma",
            "Simon van Heeringen",
            "Spencer Galen",
            "Sujai Kumar",
            "Tara Pelletier",
            "Theresa Ryan",
            "thibautbrunet",
            "Valla Bernhardt",
            "vrruki",
            "xwingpioletresar",
        ],
    },
    {
        names: ["Mattia Menchetti"],
    },
    {
        names: [
            "Alex Champagne",
            "Alexandre Marcel S. Machado",
            "Anna Garcia Forner",
            "Bradley Newsom",
            "Brendan Pinto",
            "Chamaillé Simon",
            "Dan McGregor",
            "Duncan Lock",
            "Emi Ling",
            "Gary Coady",
            "Greg Geisler",
            "Guy Lee-Potter",
            "Jose Luis Villanueva",
            "Joseph Bonsor",
            "Kimberleigh Tommy",
            "Leonardo Ambasciano",
            "Lucy Chang",
            "Olivier Glaizot",
            "Sam Jones",
            "Sam Welch",
            "Svend Andersen",
            "tcleland27",
            "Vásárhelyi Dániel",
        ],
    },
    {
        names: [
            "Brendan Pinto",
            "Brooklynn Hall",
            "Christophe Dessimoz",
            "Jan Krag",
            "Jason Macrander",
            "Loretta Gail Siniard McClinton",
            "Mike Dickison",
            "Ryosuke Iritani",
            "Vicky Stein",
            "Yuval Polotsky",
        ],
    },
]
export default SUPPORTERS
