service: phylopic-api
useDotenv: true
provider:
    architecture: arm64
    httpApi:
        payload: "1.0"
        cors:
            allowedOrigins:
                - "*"
            allowedHeaders:
                - Accept
                - Authorization
                - Content-Type
                - Deprecation
                - Link
                - X-Amz-Date
                - X-Amz-Security-Token
                - X-Amz-User-Agent
                - X-Api-Key
        authorizers:
            auth:
                type: request
                functionName: auth
                payloadVersion: "1.0"
                identitySource:
                    - $request.header.Authorization
                resultTtlInSeconds: 0
    iam:
        role: arn:aws:iam::960039257217:role/phylopic-api-executor
    name: aws
    runtime: nodejs22.x
    region: us-west-2
    stage: prod
    versionFunctions: false
plugins:
    - serverless-offline
functions:
    auth:
        handler: src/lambdas/auth.onAPIGatewayRequestAuthorizer
        environment:
            AUTH_SECRET_KEY: "${ssm:AUTH_SECRET_KEY}"
    ping:
        handler: src/lambdas/ping.onAPIGatewayProxy
        memorySize: 128
        events:
            - httpApi:
                  path: /_ping
                  method: get
    static:
        handler: src/lambdas/static.onAPIGatewayProxy
        memorySize: 128
        environment:
            PHYLOPIC_BUILD: "${ssm:PHYLOPIC_BUILD}"
            PHYLOPIC_BUILD_TIMESTAMP: "${ssm:PHYLOPIC_BUILD_TIMESTAMP}"
            PHYLOPIC_ROOT_UUID: "${ssm:PHYLOPIC_ROOT_UUID}"
        events:
            - httpApi:
                  path: /
                  method: get
            - httpApi:
                  path: /licenses
                  method: get
            - httpApi:
                  path: /root
                  method: get
    dynamic:
        handler: src/lambdas/dynamic.onAPIGatewayProxy
        memorySize: 512
        timeout: 30
        environment:
            ENTITIES_BUCKET: entities.phylopic.org
            ENTITY_JSON_SOURCE: s3
            PGDATABASE: "${ssm:PGDATABASE}"
            PGHOST: "${ssm:PGHOST}"
            PGPASSWORD: "${ssm:PGPASSWORD}"
            PGPORT: "${ssm:PGPORT}"
            PGUSER: "${ssm:PGUSER}"
            PHYLOPIC_BUILD: "${ssm:PHYLOPIC_BUILD}"
        events:
            - httpApi:
                  path: /autocomplete
                  method: get
            - httpApi:
                  path: /collections
                  method: post
            - httpApi:
                  path: /collections/{uuid}
                  method: get
            - httpApi:
                  path: /contributors
                  method: get
            - httpApi:
                  path: /contributors/{uuid}
                  method: get
            - httpApi:
                  path: /images
                  method: get
            - httpApi:
                  path: /images/{uuid}
                  method: get
            - httpApi:
                  path: /namespaces
                  method: get
            - httpApi:
                  path: /nodes
                  method: get
            - httpApi:
                  path: /nodes/{uuid}
                  method: get
            - httpApi:
                  path: /nodes/{uuid}/lineage
                  method: get
            - httpApi:
                  path: /resolve/{authority}/{namespace}/{objectID}
                  method: get
            - httpApi:
                  path: /resolve/{authority}/{namespace}
                  method: get
            - httpApi:
                  path: /resolve/{authority}/{namespace}
                  method: post
    uploader:
        handler: src/lambdas/uploader.onAPIGatewayProxy
        memorySize: 512
        timeout: 30
        events:
            - httpApi:
                  authorizer:
                      name: auth
                  path: /uploads
                  method: post
